{{ if .Values.base.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
  labels:
    chart: '{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    release: {{ .Release.Name }}
    implementation: microprofile
spec:
  replicas: {{ .Values.base.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{  .Chart.Name }}-selector"
        release: {{ .Release.Name }}
        version: "base"
        implementation: microprofile
    spec:
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.base.image.tag }}"
        imagePullPolicy: Always
{{ if .Values.istio.enabled }}
{{ else }}
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 1500
          timeoutSeconds: 500
{{ end }}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: PORT
            value: "{{ .Values.service.servicePort }}"
          - name: zipkinHost
            value: "{{ .Release.Name }}-{{ .Values.service.zipkinName }}"
          - name: zipkinPort
            value: "{{ .Values.service.zipkinPort }}"
{{ end }}
