{{- if and (not .Values.mysql.existingSecret) .Values.mysql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}-mysql-secret
  labels:
    chart: '{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    release: {{ .Release.Name }}
    implementation: microprofile
type: Opaque
data:
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
{{- end }}
