apiVersion: v1
kind: Service
metadata:
  annotations:
    bluecompute: "true"
    #prometheus.io/scrape: "true"
  name: {{ .Release.Name }}-{{ .Values.service.name }}
  labels:
    chart: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    implementation: microprofile
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.servicePort }}
  - name: https
    port: {{ .Values.service.servicePortHttps }}
  selector:
    app: "{{ .Release.Name }}-{{  .Chart.Name }}-selector"
    release: {{ .Release.Name }}
    implementation: microprofile
